// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace Pre_maritalCounSeling.DAL.Entities;

public partial class NET1718_PRN231_PRJ_G2_PremaritalCounselingContext : DbContext
{
    private readonly IConfiguration _configuration;
    public NET1718_PRN231_PRJ_G2_PremaritalCounselingContext()
    {
    }

    public NET1718_PRN231_PRJ_G2_PremaritalCounselingContext(DbContextOptions<NET1718_PRN231_PRJ_G2_PremaritalCounselingContext> options, IConfiguration configuration)
        : base(options)
    {
        _configuration = configuration;
    }
    #region Basic Get ConnectionString
    //public static string GetConnectionString(string connectionStringName)
    //{
    //    var config = new ConfigurationBuilder()
    //        .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
    //        .AddJsonFile("appsettings.json")
    //        .Build();

    //    string connectionString = config.GetConnectionString(connectionStringName);
    //    return connectionString;
    //}
    #endregion

    public string GetConnectionString(string connectionStringName)
    => _configuration.GetConnectionString(connectionStringName);

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //=> optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection"));
    #region Uncomment for running Migration CLIS
    => optionsBuilder.UseSqlServer("Data Source=KH8I_NG8_NE\\KH8I01INSTANCE;Initial Catalog=NET1718_PRN231_PRJ_G2_PremaritalCounseling;User ID=sa;Password=123456;Encrypt=False");
    #endregion
    public virtual DbSet<AttachedFile> AttachedFiles { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<FeedbackType> FeedbackTypes { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<PostType> PostTypes { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<QuestionOption> QuestionOptions { get; set; }

    public virtual DbSet<Quiz> Quizzes { get; set; }

    public virtual DbSet<QuizResult> QuizResults { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }

    public virtual DbSet<ScheduleType> ScheduleTypes { get; set; }

    public virtual DbSet<ScheduleUser> ScheduleUsers { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<ServiceCategory> ServiceCategories { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserDetail> UserDetails { get; set; }

    public virtual DbSet<UserDetailCategory> UserDetailCategories { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AttachedFile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("attached_file_id_primary");

            entity.ToTable("Attached_File");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.FeedbackId).HasColumnName("feedback_id");
            entity.Property(e => e.ReferedLink)
                .HasColumnType("text")
                .HasColumnName("refered_link")
                .IsRequired();
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(255)
                .IsRequired()
                .HasColumnName("type");

            entity.HasOne(d => d.Feedback).WithMany(p => p.AttachedFiles)
                .HasForeignKey(d => d.FeedbackId)
                .HasConstraintName("attached_file_feedback_id_foreign");

            entity.HasOne(d => d.Schedule).WithMany(p => p.AttachedFiles)
              .HasForeignKey(d => d.ScheduleId)
              .HasConstraintName("attached_file_schedule_id_foreign");
            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("feedback_id_primary");

            entity.ToTable("Feedback");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("content");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.ServiceId).HasColumnName("service_id");
            entity.Property(e => e.TypeId).HasColumnName("type_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("user_name");

            entity.HasOne(d => d.Service).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.ServiceId)
                .HasConstraintName("feedback_service_id_foreign");

            entity.HasOne(d => d.Type).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.TypeId)
                .HasConstraintName("feedback_type_id_foreign");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<FeedbackType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("feedback_type_id_primary");

            entity.ToTable("Feedback_Type");

            entity.HasIndex(e => e.Name, "feedback_type_name_unique").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("post_id_primary");

            entity.ToTable("Post");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("content");
            entity.Property(e => e.Title).HasColumnName("title").IsRequired();
            entity.Property(e => e.TypeId).HasColumnName("type_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.UserName)
                .HasMaxLength(255)
                .IsRequired()
                .HasColumnName("user_name");
            entity.Property(e => e.View).HasColumnName("view");

            entity.HasOne(d => d.Type).WithMany(p => p.Posts)
                .HasForeignKey(d => d.TypeId)
                .HasConstraintName("post_type_id_foreign");

            entity.HasOne(d => d.User).WithMany(p => p.Posts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("post_user_id_foreign");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<PostType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("post_type_id_primary");

            entity.ToTable("Post_Type");

            entity.HasIndex(e => e.Name, "post_type_name_unique").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("question_id_primary");

            entity.ToTable("Question");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("content");
            entity.Property(e => e.Image)
                .HasColumnType("text")
                .HasColumnName("image");
            entity.Property(e => e.QuestionType).HasColumnName("question_type");
            entity.Property(e => e.RecommendedAnswer)
                .HasColumnType("text")
                .HasColumnName("recommended_answer");

            entity.HasOne(d => d.Quiz).WithMany(p => p.Questions)
           .HasForeignKey(d => d.QuizId)
           .HasConstraintName("question_id_foreign");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<QuestionOption>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("question_option_id_primary");

            entity.ToTable("Question_Option");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("content");
            entity.Property(e => e.Explanation)
                .HasColumnType("text")
                .HasColumnName("explanation");
            entity.Property(e => e.IsCorrect).HasColumnName("is_correct").IsRequired();
            entity.Property(e => e.QuestionId).HasColumnName("question_id");
            entity.HasOne(d => d.Question).WithMany(p => p.QuestionOptions)
                .HasForeignKey(d => d.QuestionId)
                .HasConstraintName("question_option_id_foreign");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<Quiz>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("quiz_id_primary");

            entity.ToTable("Quiz");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.AvgTimeCompleted).HasColumnName("avg_time_completed");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.Difficulty)
                .HasMaxLength(255)
                .HasColumnName("difficulty");
            entity.Property(e => e.Duration).HasColumnName("duration");
            entity.Property(e => e.DurationUnit)
                .HasMaxLength(255)
                .HasColumnName("duration_unit");
            entity.Property(e => e.Image)
                .HasColumnType("text")
                .HasColumnName("image");
            entity.Property(e => e.PassScore).HasColumnName("pass_score");
            entity.Property(e => e.Tags)
                .HasColumnType("text")
                .HasColumnName("tags");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("title");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<QuizResult>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("quiz_result_id_primary");

            entity.ToTable("Quiz_Result");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.AttemptTime).HasColumnName("attempt_time").IsRequired();
            entity.Property(e => e.QuizId).HasColumnName("quiz_id");
            entity.Property(e => e.QuizResultCode)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("quiz_result_code");
            entity.Property(e => e.Score).HasColumnName("score").IsRequired();
            entity.Property(e => e.TimeCompleted).HasColumnName("time_completed").IsRequired();
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.SuggestionContent)
                .HasColumnType("text")
                .HasColumnName("suggestion_content");

            entity.HasOne(d => d.Quiz)
                .WithMany(p => p.QuizResults)
                .HasForeignKey(d => d.QuizId)
                .HasConstraintName("quiz_result_quiz_id_foreign");

            entity.HasOne(d => d.User)
                .WithMany(p => p.QuizResults)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("quiz_result_user_id_foreign");

            entity.Property(e => e.DoHaveFeedback).HasDefaultValue(false);
            entity.Property(e => e.FeedBack).HasDefaultValue("No feedback provided yet!");
            entity.Property(e => e.UserAnswerData).HasColumnType("text");
            entity.Property(e => e.RecommendedAnswerData).HasColumnType("text");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("role_id_primary");

            entity.ToTable("Role");

            entity.HasIndex(e => e.Name, "role_name_unique").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("schedule_id_primary");

            entity.ToTable("Schedule");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.AppointmentMode)
                .HasMaxLength(255)
                .HasColumnName("appointment_mode");
            entity.Property(e => e.CompletedAt)
                .HasColumnName("completed_at");
            entity.Property(e => e.CustomerNote)
                .HasColumnType("text")
                .HasColumnName("customer_note");
            entity.Property(e => e.ExpertNote)
                .HasColumnType("text")
                .HasColumnName("expert_note");
            entity.Property(e => e.ExpertResponse)
                .HasColumnType("text")
                .HasColumnName("expert_response");
            entity.Property(e => e.Location)
                .HasColumnType("text")
                .HasColumnName("location");
            entity.Property(e => e.Priority)
                .HasMaxLength(255)
                .HasColumnName("priority");
            entity.Property(e => e.ReferedLink)
                .HasColumnType("text")
                .HasColumnName("refered_link");
            entity.Property(e => e.ReminderSent).HasColumnName("reminder_sent").IsRequired();
            entity.Property(e => e.RescheduledCount).HasColumnName("rescheduled_count").IsRequired();
            entity.HasCheckConstraint("CK_RescheduledCount_Max", "rescheduled_count <= 2");
            entity.Property(e => e.RescheduledTime)
                .HasColumnType("datetime")
                .HasColumnName("rescheduled_time");
            entity.Property(e => e.ScheduleTypeId).HasColumnName("schedule_type_id");
            entity.Property(e => e.ServiceId).HasColumnName("service_id");
            entity.Property(e => e.Time)
                .HasColumnType("datetime")
                .IsRequired()
                .HasColumnName("time");

            entity.HasOne(d => d.ScheduleType).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.ScheduleTypeId)
                .HasConstraintName("schedule_schedule_type_id_foreign");

            entity.HasOne(d => d.Service).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.ServiceId)
                .HasConstraintName("schedule_service_id_foreign");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<ScheduleType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("schedule_type_id_primary");

            entity.ToTable("Schedule_Type");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.Buffer).HasColumnName("buffer");
            entity.Property(e => e.BufferUnit)
                .HasMaxLength(255)
                .HasColumnName("buffer_unit");
            entity.Property(e => e.EndDate).HasColumnName("end_date").IsRequired();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.StartDate).HasColumnName("start_date").IsRequired();

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<ScheduleUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("schedule_user_id_primary");

            entity.ToTable("Schedule_User");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.ScheduleId).HasColumnName("schedule_id");

            entity.HasOne(d => d.Customer).WithMany(p => p.ScheduleUsers)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("schedule_user_customer_id_foreign")
                .OnDelete(DeleteBehavior.NoAction);

            entity.HasOne(d => d.Schedule).WithMany(p => p.ScheduleUsers)
                .HasForeignKey(d => d.ScheduleId)
                .HasConstraintName("schedule_user_schedule_id_foreign")
                .OnDelete(DeleteBehavior.NoAction); ;

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<Service>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("service_id_primary");

            entity.ToTable("Service");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.AvgRating).HasColumnName("avg_rating");
            entity.HasCheckConstraint("Max_value_avg_rating", "avg_rating <= 5");
            entity.HasCheckConstraint("Min_value_avg_rating", "avg_rating >= 0");
            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.Commission).HasColumnName("commission");
            entity.Property(e => e.CommissionRate).HasColumnName("commission_rate");
            entity.HasCheckConstraint("Min_value_commission_rate", "commission_rate >= 0");
            entity.Property(e => e.Currency)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("currency");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description")
                .IsRequired();
            entity.Property(e => e.DurationUnit)
                .HasMaxLength(255)
                .HasColumnName("duration_unit");
            entity.Property(e => e.EstimatedDuration).HasColumnName("estimated_duration");
            entity.Property(e => e.ExpertId).HasColumnName("expert_id");
            entity.Property(e => e.Image)
                .HasColumnType("text")
                .HasColumnName("image");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Price).HasColumnName("price").IsRequired();
            entity.Property(e => e.ServiceCode).HasColumnName("service_code").IsRequired();

            entity.HasOne(d => d.Category).WithMany(p => p.Services)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("service_category_id_foreign");

            entity.HasOne(d => d.Expert).WithMany(p => p.Services)
                .HasForeignKey(d => d.ExpertId)
                .HasConstraintName("service_expert_id_foreign");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<ServiceCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("service_category_id_primary");

            entity.ToTable("Service_Category");

            entity.HasIndex(e => e.Name, "service_category_name_unique").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.CategoryCode)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("category_code");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.Image)
                .HasColumnType("text")
                .HasColumnName("image");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("user_id_primary");

            entity.ToTable("User");
            //TODO: check mail + phone used for active account or not
            entity.HasIndex(e => e.UserName, "user_user_name_unique").IsUnique();
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.ApplicationCode)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("application_code");
            entity.Property(e => e.Avatar)
                .HasColumnType("text")
                .HasColumnName("avatar");
            entity.Property(e => e.BackgroundImg)
                .HasColumnType("text")
                .HasColumnName("background_img");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("employee_code");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("full_name");
            entity.Property(e => e.PartnerId).HasColumnName("partner_id");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.RequestCode)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("request_code");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("user_name");
            entity.Property(e => e.RefreshToken);
            entity.Property(e => e.RefreshTokenExpiryTime);
            entity.HasOne(d => d.PartnerUser)
            //.WithOne(entity => entity.PartnerUser)
            .WithOne()
            .HasForeignKey<User>(d => d.PartnerId)
                .HasConstraintName("user_partner_id_foreign");
            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("user_role_id_foreign");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<UserDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("user_detail_id_primary");

            entity.ToTable("User_Detail");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.AttachedDocument)
                .HasColumnType("text")
                .HasColumnName("attached_document");
            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.EndDate)
                .HasColumnType("datetime")
                .HasColumnName("end_date");
            entity.Property(e => e.Image)
                .HasColumnType("text")
                .HasColumnName("image");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("name");
            entity.Property(e => e.ReferedLink)
                .HasColumnType("text")
                .HasColumnName("refered_link");
            entity.Property(e => e.StartDate)
                .HasColumnType("datetime")
                .HasColumnName("start_date");
            entity.Property(e => e.Summary)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("summary");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Category).WithMany(p => p.UserDetails)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("user_detail_category_id_foreign");

            entity.HasOne(d => d.User).WithMany(p => p.UserDetails)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("user_detail_user_id_foreign");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        modelBuilder.Entity<UserDetailCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("user_detail_category_id_primary");

            entity.ToTable("User_Detail_Category");

            entity.HasIndex(e => e.Name, "user_detail_category_name_unique").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.Image)
                .HasColumnType("text")
                .HasColumnName("image");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");

            #region apply base entity fields

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ModifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("modified_at");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.IsActive).HasColumnName("is_active").HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);

            #endregion
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}