// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GRPCService02.Models;

public partial class DemoQrc
{
    public int Id { get; set; }

    public string QrcodeGen { get; set; }

    public bool IsSynced { get; set; }
}