// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GRPCService02.Models;

public partial class DEMO_PRN3_GRPCContext : DbContext
{
    public DEMO_PRN3_GRPCContext(DbContextOptions<DEMO_PRN3_GRPCContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DemoQrc> DemoQrcs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DemoQrc>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DemoQRC__3214EC073364E399");

            entity.ToTable("DemoQRC");

            entity.Property(e => e.QrcodeGen).HasColumnName("QRCodeGen");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}