// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pre_maritalCounSeling.DAL.Base;
using System;
using System.Collections.Generic;

namespace Pre_maritalCounSeling.DAL.Entities;

public partial class Feedback : BaseEntity
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public string UserName { get; set; }

    public short? Rating { get; set; }

    public long TypeId { get; set; }
    //if the type is not rating only then the content must not be null or empty
    public string Content { get; set; }

    public long ServiceId { get; set; }

    public virtual ICollection<AttachedFile> AttachedFiles { get; set; } = new List<AttachedFile>();

    public virtual Service Service { get; set; }

    public virtual FeedbackType Type { get; set; }
}