// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pre_maritalCounSeling.DAL.Base;
using System;
using System.Collections.Generic;

namespace Pre_maritalCounSeling.DAL.Entities;

public partial class Post : BaseEntity
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public string UserName { get; set; }

    public string Content { get; set; }

    public long TypeId { get; set; }

    public long? View { get; set; } = 0;

    public string Title { get; set; }

    public virtual PostType Type { get; set; }

    public virtual User User { get; set; }
}