// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pre_maritalCounSeling.DAL.Base;
using System;
using System.Collections.Generic;

namespace Pre_maritalCounSeling.DAL.Entities;

public partial class QuestionOption : BaseEntity
{
    public long Id { get; set; }

    public string Content { get; set; }

    public bool IsCorrect { get; set; }

    public long QuestionId { get; set; }

    public string? Explanation { get; set; } = "No explanation yet!";

    public virtual Question Question { get; set; }
}