// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pre_maritalCounSeling.DAL.Base;
using System;
using System.Collections.Generic;

namespace Pre_maritalCounSeling.DAL.Entities;

public partial class QuizResult : BaseEntity
{
    public long Id { get; set; }

    public long Score { get; set; }

    public long QuizId { get; set; }

    public long UserId { get; set; }

    public string QuizResultCode { get; set; } = "RESULT-" + Guid.NewGuid().ToString();

    public double TimeCompleted { get; set; }

    public long AttemptTime { get; set; } = 0;

    public virtual Quiz Quiz { get; set; }

    public virtual ICollection<QuizResultDetail> QuizResultDetails { get; set; } = new List<QuizResultDetail>();

    public virtual ICollection<QuizSuggestion> QuizSuggestions { get; set; } = new List<QuizSuggestion>();

    public virtual User User { get; set; }
}