// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pre_maritalCounSeling.DAL.Base;
using System;
using System.Collections.Generic;

namespace Pre_maritalCounSeling.DAL.Entities;

public partial class QuizQuestion : BaseEntity
{
    public long Id { get; set; }

    public long QuizId { get; set; }

    public long QuestionId { get; set; }

    public virtual Question Question { get; set; }

    public virtual Quiz Quiz { get; set; }
}