// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pre_maritalCounSeling.DAL.Base;
using System;
using System.Collections.Generic;

namespace Pre_maritalCounSeling.DAL.Entities;

public partial class QuizSuggestion : BaseEntity
{
    public long Id { get; set; }
    //can be from AI, from Admin, from Expert ...
    public string Type { get; set; }

    public long? ExpertId { get; set; }

    public string? ExpertName { get; set; }

    public string Content { get; set; }

    public long QuizResultId { get; set; }

    public virtual QuizResult QuizResult { get; set; }
}