// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pre_maritalCounSeling.DAL.Base;
using System;
using System.Collections.Generic;

namespace Pre_maritalCounSeling.DAL.Entities;

public partial class ScheduleType : BaseEntity
{
    public long Id { get; set; }

    public string Name { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public long? Buffer { get; set; }

    public string? BufferUnit { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}