// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pre_maritalCounSeling.DAL.Base;
using System;
using System.Collections.Generic;

namespace Pre_maritalCounSeling.DAL.Entities;

public partial class ServiceCategory : BaseEntity
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string? Description { get; set; }

    public string? Image { get; set; }

    public string CategoryCode { get; set; } = "CATEGORY-" + Guid.NewGuid().ToString().ToUpper();

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();
}