// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pre_maritalCounSeling.DAL.Base;
using System;
using System.Collections.Generic;

namespace Pre_maritalCounSeling.DAL.Entities;

public partial class UserDetail : BaseEntity
{
    public long Id { get; set; }

    public string Summary { get; set; }

    public string Name { get; set; }

    public string? ReferedLink { get; set; }

    public string? AttachedDocument { get; set; }

    public string? Image { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public long CategoryId { get; set; }

    public long UserId { get; set; }

    public virtual UserDetailCategory Category { get; set; }

    public virtual User User { get; set; }
}