// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pre_maritalCounSeling.DAL.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Pre_maritalCounSeling.DAL.Entities;

public partial class User : BaseEntity
{
    private static readonly string DefaultAvatarString = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fstock.adobe.com%2Fsearch%3Fk%3Ddefault%2Bavatar&psig=AOvVaw3wjZa2UeEe9oo8SmDcVeTr&ust=1737121712270000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCIjskOuw-ooDFQAAAAAdAAAAABAE";
    public long Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    [RegularExpression(@"^[^@\s]+@[^@\s]+\.[^@\s]+$", ErrorMessage = "Invalid email format")]
    public string Email { get; set; }

    public string Phone { get; set; }

    public string EmployeeCode { get; set; } = "EMP-" + Guid.NewGuid().ToString();

    public short RoleId { get; set; }

    public string RequestCode { get; set; } = "REQ-" + Guid.NewGuid().ToString();

    public string ApplicationCode { get; set; } = "APP-" + Guid.NewGuid().ToString();

    public string? Avatar { get; set; } = DefaultAvatarString;

    public string? BackgroundImg { get; set; }

    public string? RefreshToken { get; set; }

    public DateTime RefreshTokenExpiryTime { get; set; }

    public long? PartnerId { get; set; }

    public virtual User PartnerUser { get; set; }

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<QuizResult> QuizResults { get; set; } = new List<QuizResult>();

    public virtual Role Role { get; set; }

    public virtual ICollection<ScheduleUser> ScheduleUsers { get; set; } = new List<ScheduleUser>();

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();

    public virtual ICollection<UserDetail> UserDetails { get; set; } = new List<UserDetail>();
}